version: '3.8'

services:
  app:
    build: .
    container_name: comparei-servico-proconf
    ports:
      - "8083:8083"
    depends_on:
      - mongo-proconf
      - redis
    networks:
      - net_proconf
      - comparei_net
    command: ["./wait-for-it.sh", "mongo-proconf:27017", "--", "./main"]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
  mongo-proconf:
    image: mongo:latest
    container_name: mongo-proconf
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: proconfdb
      MONGO_INITDB_DATABASE: proconfdb
    volumes:
      - ./data/mongo:/data/db
    networks:
      - net_proconf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
  redis:
    image: redis:7
    container_name: redis_proconf
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - net_proconf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "768M"
          
networks:
  net_proconf:
    driver: bridge
  
  comparei_net:
    external: true
